apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: external-secrets
deploy:
  helm:
    releases:
      - name: external-secrets
        namespace: external-secrets
        remoteChart: external-secrets
        repo: "https://charts.external-secrets.io"
        upgradeOnChange: true