apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-store
  namespace: secret-store-namespace
spec:
  provider:
    gcpsm:
      auth:
        workloadIdentity:
          clusterLocation: europe-west2-c
          clusterName: breadnet-cluster
          clusterProjectID: breadnet-gke
          serviceAccountRef:
            name: secret-accessor
      projectID: breadnet-secrets