#ROOT_SOURCE/namespaces/NAMESPACE/repo-sync.yaml
apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: ppc-ibm-licensing
  namespace: config-management-system
spec:
  sourceType: git
  # Since this is for a namespace repository, the format is unstructured
  sourceFormat: unstructured
  git:
    repo: https://github.com/cr-tech-repo/ibm-licensing-operator.git
    branch: latest
    auth: none
    dir: config/default
