#ROOT_SOURCE/namespaces/NAMESPACE/repo-sync.yaml
apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  name: ppc-java-backend
  namespace: ppc-java-backend-ns
spec:
  sourceType: git
  # Since this is for a namespace repository, the format is unstructured
  sourceFormat: unstructured
  git:
    repo: https://dev.azure.com/SOM-EDCIM/EIAM/_git/ppc-java-backed-microservice-test-repo
    branch: cicd-test
    auth: token
    secretRef:
      name: reimersb-ado-token
