#ROOT_SOURCE/namespaces/NAMESPACE/repo-sync.yaml
apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  name: ppc-java-backend
  namespace: ppc-java-backend-ns
spec:
  sourceType: git
  # Since this is for a namespace repository, the format is unstructured
  sourceFormat: unstructured
  git:
    repo: git@ssh.dev.azure.com:v3/SOM-EDCIM/EIAM/ppc-java-backed-microservice-test-repo
    branch: cicd-test
    auth: ssh
    secretRef:
      name: reimersb-ado-ssh
