apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
namespace: bio-verify-ns
patches:
- path: patch-app.yaml
  target:
    kind: Deployment
- path: patch-service.yaml
  target:
    kind: Service
