apiVersion: v1
kind: Service
metadata:
  name: bio-verify-service
spec:
  ports:
  - port: 80
    $patch: delete
  - name: http
    port: 80
    targetPort: 9080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 9443