#ROOT_SOURCE/namespaces/NAMESPACE/repo-sync.yaml
apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  name: ppc-hello-world
  namespace: hello-world
spec:
  sourceType: git
  # Since this is for a namespace repository, the format is unstructured
  sourceFormat: unstructured
  git:
    repo: https://github.com/cr-tech-repo/ppc-hello-world.git
    branch: main
    auth: none
