#ROOT_SOURCE/namespaces/NAMESPACE/repo-sync.yaml
apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: ppc-liberty-operator
spec:
  sourceType: git
  # Since this is for a namespace repository, the format is unstructured
  sourceFormat: unstructured
  git:
    repo: https://github.com/WASdev/websphere-liberty-operator.git
    branch: 1.2.2
    auth: none
    dir: deploy/releases/1.2.1/kustomize/overlays/watch-all-namespaces
    