apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iag-pvc-1
  namespace: iag-namespace
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: iag-pv-1
  storageClassName: iag-storage-bucket-class