apiVersion: v1
kind: PersistentVolume
metadata:
  name: iag-pv
spec:
  capacity:
    storage: 2Gi # Adjust size as per your requirement
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # or Delete as per your preference
  storageClassName: manual # Specify your storage class here
  hostPath:
    path: "/mnt/data" # The path on the host where data is stored