apiVersion: v1
kind: PersistentVolume
metadata:
  name: iag-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: iag-storage-bucket-class
  claimRef:
    namespace: iag-namespace
    name: iag-pvc
  mountOptions:
    - implicit-dirs
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: milogin-sb-static
    readOnly: true