apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iag-pvc
  namespace: iag-namespace
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: iag-pv
  storageClassName: iag-storage-bucket-class