apiVersion: v1
kind: PersistentVolume
metadata:
  name: iag-pv-1
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: iag-storage-bucket-class
  claimRef:
    namespace: iag-namespace
    name: iag-pvc-1
  mountOptions:
    - only-dir=pages
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: milogin-sb-static