apiVersion: apps/v1
kind: Deployment
metadata:
  name: iag-pub-instance
  labels:
    app: iag-pub-instance
spec:
  selector:
    matchLabels:
      app: iag-pub-instance
  replicas: 1
  template: 
    metadata:
      labels:
        app: iag-pub-instance
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      serviceAccountName: ibm-application-gateway
      securityContext:
        runAsUser: 1001
        runAsGroup: 2002
        fsGroup: 3003
      volumes:
        - name: pub-iag-configmap
          configMap:
            name: pub-iag-configmap
        - name: iag-storage-mount
          persistentVolumeClaim:
            claimName: iag-pvc-1 # This should match the name of your PVC
      containers:
        - name: iag-instance
          image: icr.io/ibmappgateway/ibm-application-gateway:23.04.0
          volumeMounts:
            - name: pub-iag-configmap
              mountPath: /var/iag/config/
            - name: iag-storage-mount
              mountPath: /var/iag/config/pages/
              readOnly: false
            - name: iag-storage-mount
              mountPath: /var/iag/logs/
              readOnly: false
          readinessProbe:
            exec:
              command:
              - /sbin/health_check.sh
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
              - /sbin/health_check.sh
            initialDelaySeconds: 120
            periodSeconds: 20

