apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: iag-external-route
spec:
  parentRefs:
  - name: iag-external-application-gateway
  hostnames:
  - "*"
  rules:
  - backendRefs:
    - name: iag-pub-instance-service
      port: 443