apiVersion: networking.gke.io/v1
kind: GCPGatewayPolicy
metadata:
  name: gateway-ssl-policy
spec:
  default:
    sslPolicy: gke-ingress-ssl-policy
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: iag-external-application-gateway
