apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: iag-backendconfig
spec:
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 50
  securityPolicy:
    name: "gcp-cloud-armor-policy-test"
  internal: true