apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iag-pub-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: iag-service
            port:
              number: 443